/*
 * generated by Xtext 2.10.0
 */
package org.boomslang.dsl.feature.tests

import com.google.inject.Inject
import org.boomslang.dsl.feature.feature.BFeaturePackage
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import org.eclipse.xtext.resource.XtextResourceSet
import org.junit.Test
import org.junit.runner.RunWith

import org.eclipse.emf.common.util.URI
import org.eclipse.xtext.junit4.AbstractXtextTests

@RunWith(XtextRunner)
@InjectWith(FeatureInjectorProviderCustom)
class FeatureParsingTest extends AbstractXtextTests{

	@Inject
	extension ParseHelper<BFeaturePackage> parser

	@Inject
	extension ValidationTestHelper

	@Inject
	XtextResourceSet xtextResourceSet

	@Test
	def void testParseMinimalSample() {
		'feature/samples/Minimal.feature'.readFileIntoString().parse().assertNoErrors
	}

	@Test
	def void testParseMaxSample() {
		xtextResourceSet.loadLoginScreen()
		'feature/samples/Login.feature'.readFileIntoString().parse(xtextResourceSet).assertNoErrors
	}

	@Test
	def void testInvalid() {
		val issues = 'feature/samples/Invalid.feature'.readFileIntoString.parse.validate
		assertEquals(1, issues.size)
		assertTrue(issues.get(0).message.contains("mismatched input '<EOF>' expecting"))
	}
	
	def loadLoginScreen(XtextResourceSet xtextResourceSet) {
		xtextResourceSet.getResource(URI.createURI("classpath:/screen/Login.screen"), true).load(null)
	}


}
