/*
 * generated by Xtext 2.10.0
 */
package org.boomslang.dsl.mapping.tests

import com.google.inject.Inject
import org.boomslang.core.BPackage
import org.eclipse.emf.common.util.URI
import org.eclipse.xtext.junit4.AbstractXtextTests
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.eclipse.xtext.resource.XtextResourceSet
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.junit4.validation.ValidationTestHelper

@RunWith(XtextRunner)
@InjectWith(MappingInjectorProviderCustom)
class MappingParsingTest extends AbstractXtextTests{

	@Inject
	extension ParseHelper<BPackage> parseHelper

	@Inject
	extension ValidationTestHelper

	@Inject
	XtextResourceSet xtextResourceSet

	@Test
	def void testFormsSimpleReferences(){
		xtextResourceSet.loadScreen("org/boomslang/test/screens/Simple.screen")
		'org/boomslang/test/mappings/Simple.mapping'.readFileIntoString().parse(xtextResourceSet).assertNoErrors
	}
	
	/**
	 * Name with pending .screen
	 */
	def loadScreen(XtextResourceSet xtextResourceSet, String name) {
		xtextResourceSet.getResource(URI.createURI("classpath:/"+name), true).load(null)
	}

}
	