<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="org.boomslang.core" nsPrefix="core">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.boomslang"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2011/Xcore">
    <details key="GenModel" value="http://www.eclipse.org/emf/2002/GenModel"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BNamedModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is a Boomslang element that can be referenced by name."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPackage" eSuperTypes="#//BNamedModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is a container for Boomslang packageable elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bImports" upperBound="-1"
        eType="#//BImport" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BImport">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is an imported namespace."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
